#!/bin/sh

# Rebuilds all patches (in IntelliJ, right-click -> Run 'rebuild')

cd ..
./gradlew rebuildPaperApiFeaturePatches # includes rebuildPaperApiFilePatches
./gradlew rebuildPaperSingleFilePatches
./gradlew :spout-server:rebuildMinecraftFeaturePatches # includes :spout-server:rebuildMinecraftFilePatches, which includes :spout-server:rebuildMinecraftResourcePatches and :spout-server:rebuildMinecraftSourcePatches
./gradlew :spout-server:rebuildPaperServerFeaturePatches # includes :spout-server:rebuildPaperServerFilePatches
cd gradle-bin
